# fly.toml app configuration file generated for rfi-gateway on 2025-03-10T16:43:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rfi-gateway'
primary_region = 'gru'

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    hard_limit = 25
    soft_limit = 20
  
  [[http_service.checks]]
    grace_period = "10s"
    interval = 10000
    timeout = 2000
    path = "/"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
